// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.bam.flutter_lyra.android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LyraApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class ErrorCodesInterface (
  val paymentCancelledByUser: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ErrorCodesInterface {
      val paymentCancelledByUser = pigeonVar_list[0] as String
      return ErrorCodesInterface(paymentCancelledByUser)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paymentCancelledByUser,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ErrorCodesInterface
    return LyraApiPigeonUtils.deepEquals(this.paymentCancelledByUser, other.paymentCancelledByUser)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.paymentCancelledByUser)
    return result
  }
  override fun toString(): String {
    return "ErrorCodesInterface(paymentCancelledByUser=$paymentCancelledByUser)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LyraInitializeOptionsInterface (
  val apiServerName: String,
  val nfcEnabled: Boolean? = null,
  val cardScanningEnabled: Boolean? = null,
  val applePayMerchantId: String? = null,
  val applePayMerchantName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LyraInitializeOptionsInterface {
      val apiServerName = pigeonVar_list[0] as String
      val nfcEnabled = pigeonVar_list[1] as Boolean?
      val cardScanningEnabled = pigeonVar_list[2] as Boolean?
      val applePayMerchantId = pigeonVar_list[3] as String?
      val applePayMerchantName = pigeonVar_list[4] as String?
      return LyraInitializeOptionsInterface(apiServerName, nfcEnabled, cardScanningEnabled, applePayMerchantId, applePayMerchantName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiServerName,
      nfcEnabled,
      cardScanningEnabled,
      applePayMerchantId,
      applePayMerchantName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LyraInitializeOptionsInterface
    return LyraApiPigeonUtils.deepEquals(this.apiServerName, other.apiServerName) && LyraApiPigeonUtils.deepEquals(this.nfcEnabled, other.nfcEnabled) && LyraApiPigeonUtils.deepEquals(this.cardScanningEnabled, other.cardScanningEnabled) && LyraApiPigeonUtils.deepEquals(this.applePayMerchantId, other.applePayMerchantId) && LyraApiPigeonUtils.deepEquals(this.applePayMerchantName, other.applePayMerchantName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.apiServerName)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.nfcEnabled)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.cardScanningEnabled)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.applePayMerchantId)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.applePayMerchantName)
    return result
  }
  override fun toString(): String {
    return "LyraInitializeOptionsInterface(apiServerName=$apiServerName, nfcEnabled=$nfcEnabled, cardScanningEnabled=$cardScanningEnabled, applePayMerchantId=$applePayMerchantId, applePayMerchantName=$applePayMerchantName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LyraKeyInterface (
  val publicKey: String,
  val options: LyraInitializeOptionsInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LyraKeyInterface {
      val publicKey = pigeonVar_list[0] as String
      val options = pigeonVar_list[1] as LyraInitializeOptionsInterface
      return LyraKeyInterface(publicKey, options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicKey,
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LyraKeyInterface
    return LyraApiPigeonUtils.deepEquals(this.publicKey, other.publicKey) && LyraApiPigeonUtils.deepEquals(this.options, other.options)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.publicKey)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.options)
    return result
  }
  override fun toString(): String {
    return "LyraKeyInterface(publicKey=$publicKey, options=$options)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LyraProcessOptionsInterface (
  val customPayButtonLabel: String? = null,
  val customHeaderLabel: String? = null,
  val customPopupLabel: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LyraProcessOptionsInterface {
      val customPayButtonLabel = pigeonVar_list[0] as String?
      val customHeaderLabel = pigeonVar_list[1] as String?
      val customPopupLabel = pigeonVar_list[2] as String?
      return LyraProcessOptionsInterface(customPayButtonLabel, customHeaderLabel, customPopupLabel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      customPayButtonLabel,
      customHeaderLabel,
      customPopupLabel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LyraProcessOptionsInterface
    return LyraApiPigeonUtils.deepEquals(this.customPayButtonLabel, other.customPayButtonLabel) && LyraApiPigeonUtils.deepEquals(this.customHeaderLabel, other.customHeaderLabel) && LyraApiPigeonUtils.deepEquals(this.customPopupLabel, other.customPopupLabel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.customPayButtonLabel)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.customHeaderLabel)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.customPopupLabel)
    return result
  }
  override fun toString(): String {
    return "LyraProcessOptionsInterface(customPayButtonLabel=$customPayButtonLabel, customHeaderLabel=$customHeaderLabel, customPopupLabel=$customPopupLabel)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProcessRequestInterface (
  val formToken: String,
  val errorCodes: ErrorCodesInterface,
  val timeoutInSeconds: Long? = null,
  val options: LyraProcessOptionsInterface? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessRequestInterface {
      val formToken = pigeonVar_list[0] as String
      val errorCodes = pigeonVar_list[1] as ErrorCodesInterface
      val timeoutInSeconds = pigeonVar_list[2] as Long?
      val options = pigeonVar_list[3] as LyraProcessOptionsInterface?
      return ProcessRequestInterface(formToken, errorCodes, timeoutInSeconds, options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formToken,
      errorCodes,
      timeoutInSeconds,
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessRequestInterface
    return LyraApiPigeonUtils.deepEquals(this.formToken, other.formToken) && LyraApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes) && LyraApiPigeonUtils.deepEquals(this.timeoutInSeconds, other.timeoutInSeconds) && LyraApiPigeonUtils.deepEquals(this.options, other.options)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.formToken)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.errorCodes)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.timeoutInSeconds)
    result = 31 * result + LyraApiPigeonUtils.deepHash(this.options)
    return result
  }
  override fun toString(): String {
    return "ProcessRequestInterface(formToken=$formToken, errorCodes=$errorCodes, timeoutInSeconds=$timeoutInSeconds, options=$options)"
  }
}
private open class LyraApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorCodesInterface.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LyraInitializeOptionsInterface.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LyraKeyInterface.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LyraProcessOptionsInterface.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessRequestInterface.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ErrorCodesInterface -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LyraInitializeOptionsInterface -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LyraKeyInterface -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LyraProcessOptionsInterface -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ProcessRequestInterface -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LyraHostApi {
  fun initialize(lyraKey: LyraKeyInterface, callback: (Result<LyraKeyInterface>) -> Unit)
  fun getFormTokenVersion(callback: (Result<Long>) -> Unit)
  fun process(request: ProcessRequestInterface, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by LyraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LyraApiPigeonCodec()
    }
    /** Sets up an instance of `LyraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LyraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val lyraKeyArg = args[0] as LyraKeyInterface
            api.initialize(lyraKeyArg) { result: Result<LyraKeyInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LyraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LyraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.getFormTokenVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getFormTokenVersion{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LyraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LyraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.process$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ProcessRequestInterface
            api.process(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LyraApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LyraApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
