name: flutter_lyra_platform_interface
description: A common platform interface for the flutter_lyra plugin.
version: 0.5.0
homepage: https://github.com/bamlab/Flutter-Lyra
repository: https://github.com/bamlab/Flutter-Lyra

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  pigeon: ^7.0.0
