// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package tech.bam.flutter_lyra.android;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class LyraApi {

  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ErrorCodesInterface {
    private @NonNull String paymentCancelledByUser;

    public @NonNull String getPaymentCancelledByUser() {
      return paymentCancelledByUser;
    }

    public void setPaymentCancelledByUser(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"paymentCancelledByUser\" is null.");
      }
      this.paymentCancelledByUser = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ErrorCodesInterface() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ErrorCodesInterface that = (ErrorCodesInterface) o;
      return pigeonDeepEquals(paymentCancelledByUser, that.paymentCancelledByUser);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), paymentCancelledByUser};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "ErrorCodesInterface{" + "paymentCancelledByUser=" + paymentCancelledByUser + "}";
    }

    public static final class Builder {

      private @Nullable String paymentCancelledByUser;

      @CanIgnoreReturnValue
      public @NonNull Builder setPaymentCancelledByUser(@NonNull String setterArg) {
        this.paymentCancelledByUser = setterArg;
        return this;
      }

      public @NonNull ErrorCodesInterface build() {
        ErrorCodesInterface pigeonReturn = new ErrorCodesInterface();
        pigeonReturn.setPaymentCancelledByUser(paymentCancelledByUser);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(paymentCancelledByUser);
      return toListResult;
    }

    static @NonNull ErrorCodesInterface fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ErrorCodesInterface pigeonResult = new ErrorCodesInterface();
      Object paymentCancelledByUser = pigeonVar_list.get(0);
      pigeonResult.setPaymentCancelledByUser((String) paymentCancelledByUser);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LyraInitializeOptionsInterface {
    private @NonNull String apiServerName;

    public @NonNull String getApiServerName() {
      return apiServerName;
    }

    public void setApiServerName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"apiServerName\" is null.");
      }
      this.apiServerName = setterArg;
    }

    private @Nullable Boolean nfcEnabled;

    public @Nullable Boolean getNfcEnabled() {
      return nfcEnabled;
    }

    public void setNfcEnabled(@Nullable Boolean setterArg) {
      this.nfcEnabled = setterArg;
    }

    private @Nullable Boolean cardScanningEnabled;

    public @Nullable Boolean getCardScanningEnabled() {
      return cardScanningEnabled;
    }

    public void setCardScanningEnabled(@Nullable Boolean setterArg) {
      this.cardScanningEnabled = setterArg;
    }

    private @Nullable String applePayMerchantId;

    public @Nullable String getApplePayMerchantId() {
      return applePayMerchantId;
    }

    public void setApplePayMerchantId(@Nullable String setterArg) {
      this.applePayMerchantId = setterArg;
    }

    private @Nullable String applePayMerchantName;

    public @Nullable String getApplePayMerchantName() {
      return applePayMerchantName;
    }

    public void setApplePayMerchantName(@Nullable String setterArg) {
      this.applePayMerchantName = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    LyraInitializeOptionsInterface() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      LyraInitializeOptionsInterface that = (LyraInitializeOptionsInterface) o;
      return pigeonDeepEquals(apiServerName, that.apiServerName) && pigeonDeepEquals(nfcEnabled, that.nfcEnabled) && pigeonDeepEquals(cardScanningEnabled, that.cardScanningEnabled) && pigeonDeepEquals(applePayMerchantId, that.applePayMerchantId) && pigeonDeepEquals(applePayMerchantName, that.applePayMerchantName);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), apiServerName, nfcEnabled, cardScanningEnabled, applePayMerchantId, applePayMerchantName};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "LyraInitializeOptionsInterface{" + "apiServerName=" + apiServerName + ", " + "nfcEnabled=" + nfcEnabled + ", " + "cardScanningEnabled=" + cardScanningEnabled + ", " + "applePayMerchantId=" + applePayMerchantId + ", " + "applePayMerchantName=" + applePayMerchantName + "}";
    }

    public static final class Builder {

      private @Nullable String apiServerName;

      @CanIgnoreReturnValue
      public @NonNull Builder setApiServerName(@NonNull String setterArg) {
        this.apiServerName = setterArg;
        return this;
      }

      private @Nullable Boolean nfcEnabled;

      @CanIgnoreReturnValue
      public @NonNull Builder setNfcEnabled(@Nullable Boolean setterArg) {
        this.nfcEnabled = setterArg;
        return this;
      }

      private @Nullable Boolean cardScanningEnabled;

      @CanIgnoreReturnValue
      public @NonNull Builder setCardScanningEnabled(@Nullable Boolean setterArg) {
        this.cardScanningEnabled = setterArg;
        return this;
      }

      private @Nullable String applePayMerchantId;

      @CanIgnoreReturnValue
      public @NonNull Builder setApplePayMerchantId(@Nullable String setterArg) {
        this.applePayMerchantId = setterArg;
        return this;
      }

      private @Nullable String applePayMerchantName;

      @CanIgnoreReturnValue
      public @NonNull Builder setApplePayMerchantName(@Nullable String setterArg) {
        this.applePayMerchantName = setterArg;
        return this;
      }

      public @NonNull LyraInitializeOptionsInterface build() {
        LyraInitializeOptionsInterface pigeonReturn = new LyraInitializeOptionsInterface();
        pigeonReturn.setApiServerName(apiServerName);
        pigeonReturn.setNfcEnabled(nfcEnabled);
        pigeonReturn.setCardScanningEnabled(cardScanningEnabled);
        pigeonReturn.setApplePayMerchantId(applePayMerchantId);
        pigeonReturn.setApplePayMerchantName(applePayMerchantName);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(5);
      toListResult.add(apiServerName);
      toListResult.add(nfcEnabled);
      toListResult.add(cardScanningEnabled);
      toListResult.add(applePayMerchantId);
      toListResult.add(applePayMerchantName);
      return toListResult;
    }

    static @NonNull LyraInitializeOptionsInterface fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      LyraInitializeOptionsInterface pigeonResult = new LyraInitializeOptionsInterface();
      Object apiServerName = pigeonVar_list.get(0);
      pigeonResult.setApiServerName((String) apiServerName);
      Object nfcEnabled = pigeonVar_list.get(1);
      pigeonResult.setNfcEnabled((Boolean) nfcEnabled);
      Object cardScanningEnabled = pigeonVar_list.get(2);
      pigeonResult.setCardScanningEnabled((Boolean) cardScanningEnabled);
      Object applePayMerchantId = pigeonVar_list.get(3);
      pigeonResult.setApplePayMerchantId((String) applePayMerchantId);
      Object applePayMerchantName = pigeonVar_list.get(4);
      pigeonResult.setApplePayMerchantName((String) applePayMerchantName);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LyraKeyInterface {
    private @NonNull String publicKey;

    public @NonNull String getPublicKey() {
      return publicKey;
    }

    public void setPublicKey(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"publicKey\" is null.");
      }
      this.publicKey = setterArg;
    }

    private @NonNull LyraInitializeOptionsInterface options;

    public @NonNull LyraInitializeOptionsInterface getOptions() {
      return options;
    }

    public void setOptions(@NonNull LyraInitializeOptionsInterface setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"options\" is null.");
      }
      this.options = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    LyraKeyInterface() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      LyraKeyInterface that = (LyraKeyInterface) o;
      return pigeonDeepEquals(publicKey, that.publicKey) && pigeonDeepEquals(options, that.options);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), publicKey, options};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "LyraKeyInterface{" + "publicKey=" + publicKey + ", " + "options=" + options + "}";
    }

    public static final class Builder {

      private @Nullable String publicKey;

      @CanIgnoreReturnValue
      public @NonNull Builder setPublicKey(@NonNull String setterArg) {
        this.publicKey = setterArg;
        return this;
      }

      private @Nullable LyraInitializeOptionsInterface options;

      @CanIgnoreReturnValue
      public @NonNull Builder setOptions(@NonNull LyraInitializeOptionsInterface setterArg) {
        this.options = setterArg;
        return this;
      }

      public @NonNull LyraKeyInterface build() {
        LyraKeyInterface pigeonReturn = new LyraKeyInterface();
        pigeonReturn.setPublicKey(publicKey);
        pigeonReturn.setOptions(options);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(publicKey);
      toListResult.add(options);
      return toListResult;
    }

    static @NonNull LyraKeyInterface fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      LyraKeyInterface pigeonResult = new LyraKeyInterface();
      Object publicKey = pigeonVar_list.get(0);
      pigeonResult.setPublicKey((String) publicKey);
      Object options = pigeonVar_list.get(1);
      pigeonResult.setOptions((LyraInitializeOptionsInterface) options);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ProcessRequestInterface {
    private @NonNull String formToken;

    public @NonNull String getFormToken() {
      return formToken;
    }

    public void setFormToken(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"formToken\" is null.");
      }
      this.formToken = setterArg;
    }

    private @NonNull ErrorCodesInterface errorCodes;

    public @NonNull ErrorCodesInterface getErrorCodes() {
      return errorCodes;
    }

    public void setErrorCodes(@NonNull ErrorCodesInterface setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"errorCodes\" is null.");
      }
      this.errorCodes = setterArg;
    }

    private @Nullable Long timeoutInSeconds;

    public @Nullable Long getTimeoutInSeconds() {
      return timeoutInSeconds;
    }

    public void setTimeoutInSeconds(@Nullable Long setterArg) {
      this.timeoutInSeconds = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ProcessRequestInterface() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ProcessRequestInterface that = (ProcessRequestInterface) o;
      return pigeonDeepEquals(formToken, that.formToken) && pigeonDeepEquals(errorCodes, that.errorCodes) && pigeonDeepEquals(timeoutInSeconds, that.timeoutInSeconds);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), formToken, errorCodes, timeoutInSeconds};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "ProcessRequestInterface{" + "formToken=" + formToken + ", " + "errorCodes=" + errorCodes + ", " + "timeoutInSeconds=" + timeoutInSeconds + "}";
    }

    public static final class Builder {

      private @Nullable String formToken;

      @CanIgnoreReturnValue
      public @NonNull Builder setFormToken(@NonNull String setterArg) {
        this.formToken = setterArg;
        return this;
      }

      private @Nullable ErrorCodesInterface errorCodes;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorCodes(@NonNull ErrorCodesInterface setterArg) {
        this.errorCodes = setterArg;
        return this;
      }

      private @Nullable Long timeoutInSeconds;

      @CanIgnoreReturnValue
      public @NonNull Builder setTimeoutInSeconds(@Nullable Long setterArg) {
        this.timeoutInSeconds = setterArg;
        return this;
      }

      public @NonNull ProcessRequestInterface build() {
        ProcessRequestInterface pigeonReturn = new ProcessRequestInterface();
        pigeonReturn.setFormToken(formToken);
        pigeonReturn.setErrorCodes(errorCodes);
        pigeonReturn.setTimeoutInSeconds(timeoutInSeconds);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(formToken);
      toListResult.add(errorCodes);
      toListResult.add(timeoutInSeconds);
      return toListResult;
    }

    static @NonNull ProcessRequestInterface fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ProcessRequestInterface pigeonResult = new ProcessRequestInterface();
      Object formToken = pigeonVar_list.get(0);
      pigeonResult.setFormToken((String) formToken);
      Object errorCodes = pigeonVar_list.get(1);
      pigeonResult.setErrorCodes((ErrorCodesInterface) errorCodes);
      Object timeoutInSeconds = pigeonVar_list.get(2);
      pigeonResult.setTimeoutInSeconds((Long) timeoutInSeconds);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return ErrorCodesInterface.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return LyraInitializeOptionsInterface.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return LyraKeyInterface.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return ProcessRequestInterface.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof ErrorCodesInterface) {
        stream.write(129);
        writeValue(stream, ((ErrorCodesInterface) value).toList());
      } else if (value instanceof LyraInitializeOptionsInterface) {
        stream.write(130);
        writeValue(stream, ((LyraInitializeOptionsInterface) value).toList());
      } else if (value instanceof LyraKeyInterface) {
        stream.write(131);
        writeValue(stream, ((LyraKeyInterface) value).toList());
      } else if (value instanceof ProcessRequestInterface) {
        stream.write(132);
        writeValue(stream, ((ProcessRequestInterface) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface LyraHostApi {

    void initialize(@NonNull LyraKeyInterface lyraKey, @NonNull Result<LyraKeyInterface> result);

    void getFormTokenVersion(@NonNull Result<Long> result);

    void process(@NonNull ProcessRequestInterface request, @NonNull Result<String> result);

    /** The codec used by LyraHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `LyraHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable LyraHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable LyraHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.initialize" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                LyraKeyInterface lyraKeyArg = (LyraKeyInterface) args.get(0);
                Result<LyraKeyInterface> resultCallback =
                    new Result<LyraKeyInterface>() {
                      public void success(LyraKeyInterface result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.initialize(lyraKeyArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.getFormTokenVersion" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<Long> resultCallback =
                    new Result<Long>() {
                      public void success(Long result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getFormTokenVersion(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.process" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ProcessRequestInterface requestArg = (ProcessRequestInterface) args.get(0);
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.process(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
