// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class ErrorCodesInterface {
  ErrorCodesInterface({
    required this.paymentCancelledByUser,
  });

  String paymentCancelledByUser;

  List<Object?> _toList() {
    return <Object?>[
      paymentCancelledByUser,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ErrorCodesInterface decode(Object result) {
    result as List<Object?>;
    return ErrorCodesInterface(
      paymentCancelledByUser: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ErrorCodesInterface || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(paymentCancelledByUser, other.paymentCancelledByUser);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ErrorCodesInterface(paymentCancelledByUser: $paymentCancelledByUser)';
  }
}

class LyraInitializeOptionsInterface {
  LyraInitializeOptionsInterface({
    required this.apiServerName,
    this.nfcEnabled,
    this.cardScanningEnabled,
    this.applePayMerchantId,
    this.applePayMerchantName,
  });

  String apiServerName;

  bool? nfcEnabled;

  bool? cardScanningEnabled;

  String? applePayMerchantId;

  String? applePayMerchantName;

  List<Object?> _toList() {
    return <Object?>[
      apiServerName,
      nfcEnabled,
      cardScanningEnabled,
      applePayMerchantId,
      applePayMerchantName,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LyraInitializeOptionsInterface decode(Object result) {
    result as List<Object?>;
    return LyraInitializeOptionsInterface(
      apiServerName: result[0]! as String,
      nfcEnabled: result[1] as bool?,
      cardScanningEnabled: result[2] as bool?,
      applePayMerchantId: result[3] as String?,
      applePayMerchantName: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LyraInitializeOptionsInterface ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiServerName, other.apiServerName) &&
        _deepEquals(nfcEnabled, other.nfcEnabled) &&
        _deepEquals(cardScanningEnabled, other.cardScanningEnabled) &&
        _deepEquals(applePayMerchantId, other.applePayMerchantId) &&
        _deepEquals(applePayMerchantName, other.applePayMerchantName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LyraInitializeOptionsInterface(apiServerName: $apiServerName, nfcEnabled: $nfcEnabled, cardScanningEnabled: $cardScanningEnabled, applePayMerchantId: $applePayMerchantId, applePayMerchantName: $applePayMerchantName)';
  }
}

class LyraKeyInterface {
  LyraKeyInterface({
    required this.publicKey,
    required this.options,
  });

  String publicKey;

  LyraInitializeOptionsInterface options;

  List<Object?> _toList() {
    return <Object?>[
      publicKey,
      options,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LyraKeyInterface decode(Object result) {
    result as List<Object?>;
    return LyraKeyInterface(
      publicKey: result[0]! as String,
      options: result[1]! as LyraInitializeOptionsInterface,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LyraKeyInterface || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(publicKey, other.publicKey) &&
        _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LyraKeyInterface(publicKey: $publicKey, options: $options)';
  }
}

class LyraProcessOptionsInterface {
  LyraProcessOptionsInterface({
    this.customPayButtonLabel,
    this.customHeaderLabel,
    this.customPopupLabel,
  });

  String? customPayButtonLabel;

  String? customHeaderLabel;

  String? customPopupLabel;

  List<Object?> _toList() {
    return <Object?>[
      customPayButtonLabel,
      customHeaderLabel,
      customPopupLabel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LyraProcessOptionsInterface decode(Object result) {
    result as List<Object?>;
    return LyraProcessOptionsInterface(
      customPayButtonLabel: result[0] as String?,
      customHeaderLabel: result[1] as String?,
      customPopupLabel: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LyraProcessOptionsInterface ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(customPayButtonLabel, other.customPayButtonLabel) &&
        _deepEquals(customHeaderLabel, other.customHeaderLabel) &&
        _deepEquals(customPopupLabel, other.customPopupLabel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LyraProcessOptionsInterface(customPayButtonLabel: $customPayButtonLabel, customHeaderLabel: $customHeaderLabel, customPopupLabel: $customPopupLabel)';
  }
}

class ProcessRequestInterface {
  ProcessRequestInterface({
    required this.formToken,
    required this.errorCodes,
    this.timeoutInSeconds,
    this.options,
  });

  String formToken;

  ErrorCodesInterface errorCodes;

  int? timeoutInSeconds;

  LyraProcessOptionsInterface? options;

  List<Object?> _toList() {
    return <Object?>[
      formToken,
      errorCodes,
      timeoutInSeconds,
      options,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ProcessRequestInterface decode(Object result) {
    result as List<Object?>;
    return ProcessRequestInterface(
      formToken: result[0]! as String,
      errorCodes: result[1]! as ErrorCodesInterface,
      timeoutInSeconds: result[2] as int?,
      options: result[3] as LyraProcessOptionsInterface?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProcessRequestInterface || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(formToken, other.formToken) &&
        _deepEquals(errorCodes, other.errorCodes) &&
        _deepEquals(timeoutInSeconds, other.timeoutInSeconds) &&
        _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProcessRequestInterface(formToken: $formToken, errorCodes: $errorCodes, timeoutInSeconds: $timeoutInSeconds, options: $options)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ErrorCodesInterface) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is LyraInitializeOptionsInterface) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LyraKeyInterface) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is LyraProcessOptionsInterface) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ProcessRequestInterface) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ErrorCodesInterface.decode(readValue(buffer)!);
      case 130:
        return LyraInitializeOptionsInterface.decode(readValue(buffer)!);
      case 131:
        return LyraKeyInterface.decode(readValue(buffer)!);
      case 132:
        return LyraProcessOptionsInterface.decode(readValue(buffer)!);
      case 133:
        return ProcessRequestInterface.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LyraHostApi {
  /// Constructor for [LyraHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LyraHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<LyraKeyInterface> initialize(LyraKeyInterface lyraKey) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[lyraKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as LyraKeyInterface;
  }

  Future<int> getFormTokenVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.getFormTokenVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<String> process(ProcessRequestInterface request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.process$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}
