// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum LyraApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct ErrorCodesInterface: Hashable, CustomStringConvertible {
  var paymentCancelledByUser: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorCodesInterface? {
    let paymentCancelledByUser = pigeonVar_list[0] as! String

    return ErrorCodesInterface(
      paymentCancelledByUser: paymentCancelledByUser
    )
  }
  func toList() -> [Any?] {
    return [
      paymentCancelledByUser
    ]
  }
  static func == (lhs: ErrorCodesInterface, rhs: ErrorCodesInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LyraApiPigeonInternal.deepEquals(lhs.paymentCancelledByUser, rhs.paymentCancelledByUser)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ErrorCodesInterface")
    LyraApiPigeonInternal.deepHash(value: paymentCancelledByUser, hasher: &hasher)
  }

  public var description: String {
    return "ErrorCodesInterface(paymentCancelledByUser: \(String(describing: paymentCancelledByUser)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LyraInitializeOptionsInterface: Hashable, CustomStringConvertible {
  var apiServerName: String
  var nfcEnabled: Bool? = nil
  var cardScanningEnabled: Bool? = nil
  var applePayMerchantId: String? = nil
  var applePayMerchantName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LyraInitializeOptionsInterface? {
    let apiServerName = pigeonVar_list[0] as! String
    let nfcEnabled: Bool? = nilOrValue(pigeonVar_list[1])
    let cardScanningEnabled: Bool? = nilOrValue(pigeonVar_list[2])
    let applePayMerchantId: String? = nilOrValue(pigeonVar_list[3])
    let applePayMerchantName: String? = nilOrValue(pigeonVar_list[4])

    return LyraInitializeOptionsInterface(
      apiServerName: apiServerName,
      nfcEnabled: nfcEnabled,
      cardScanningEnabled: cardScanningEnabled,
      applePayMerchantId: applePayMerchantId,
      applePayMerchantName: applePayMerchantName
    )
  }
  func toList() -> [Any?] {
    return [
      apiServerName,
      nfcEnabled,
      cardScanningEnabled,
      applePayMerchantId,
      applePayMerchantName,
    ]
  }
  static func == (lhs: LyraInitializeOptionsInterface, rhs: LyraInitializeOptionsInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LyraApiPigeonInternal.deepEquals(lhs.apiServerName, rhs.apiServerName) && LyraApiPigeonInternal.deepEquals(lhs.nfcEnabled, rhs.nfcEnabled) && LyraApiPigeonInternal.deepEquals(lhs.cardScanningEnabled, rhs.cardScanningEnabled) && LyraApiPigeonInternal.deepEquals(lhs.applePayMerchantId, rhs.applePayMerchantId) && LyraApiPigeonInternal.deepEquals(lhs.applePayMerchantName, rhs.applePayMerchantName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LyraInitializeOptionsInterface")
    LyraApiPigeonInternal.deepHash(value: apiServerName, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: nfcEnabled, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: cardScanningEnabled, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: applePayMerchantId, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: applePayMerchantName, hasher: &hasher)
  }

  public var description: String {
    return "LyraInitializeOptionsInterface(apiServerName: \(String(describing: apiServerName)), nfcEnabled: \(String(describing: nfcEnabled)), cardScanningEnabled: \(String(describing: cardScanningEnabled)), applePayMerchantId: \(String(describing: applePayMerchantId)), applePayMerchantName: \(String(describing: applePayMerchantName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LyraKeyInterface: Hashable, CustomStringConvertible {
  var publicKey: String
  var options: LyraInitializeOptionsInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LyraKeyInterface? {
    let publicKey = pigeonVar_list[0] as! String
    let options = pigeonVar_list[1] as! LyraInitializeOptionsInterface

    return LyraKeyInterface(
      publicKey: publicKey,
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      publicKey,
      options,
    ]
  }
  static func == (lhs: LyraKeyInterface, rhs: LyraKeyInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LyraApiPigeonInternal.deepEquals(lhs.publicKey, rhs.publicKey) && LyraApiPigeonInternal.deepEquals(lhs.options, rhs.options)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LyraKeyInterface")
    LyraApiPigeonInternal.deepHash(value: publicKey, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: options, hasher: &hasher)
  }

  public var description: String {
    return "LyraKeyInterface(publicKey: \(String(describing: publicKey)), options: \(String(describing: options)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LyraProcessOptionsInterface: Hashable, CustomStringConvertible {
  var customPayButtonLabel: String? = nil
  var customHeaderLabel: String? = nil
  var customPopupLabel: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LyraProcessOptionsInterface? {
    let customPayButtonLabel: String? = nilOrValue(pigeonVar_list[0])
    let customHeaderLabel: String? = nilOrValue(pigeonVar_list[1])
    let customPopupLabel: String? = nilOrValue(pigeonVar_list[2])

    return LyraProcessOptionsInterface(
      customPayButtonLabel: customPayButtonLabel,
      customHeaderLabel: customHeaderLabel,
      customPopupLabel: customPopupLabel
    )
  }
  func toList() -> [Any?] {
    return [
      customPayButtonLabel,
      customHeaderLabel,
      customPopupLabel,
    ]
  }
  static func == (lhs: LyraProcessOptionsInterface, rhs: LyraProcessOptionsInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LyraApiPigeonInternal.deepEquals(lhs.customPayButtonLabel, rhs.customPayButtonLabel) && LyraApiPigeonInternal.deepEquals(lhs.customHeaderLabel, rhs.customHeaderLabel) && LyraApiPigeonInternal.deepEquals(lhs.customPopupLabel, rhs.customPopupLabel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LyraProcessOptionsInterface")
    LyraApiPigeonInternal.deepHash(value: customPayButtonLabel, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: customHeaderLabel, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: customPopupLabel, hasher: &hasher)
  }

  public var description: String {
    return "LyraProcessOptionsInterface(customPayButtonLabel: \(String(describing: customPayButtonLabel)), customHeaderLabel: \(String(describing: customHeaderLabel)), customPopupLabel: \(String(describing: customPopupLabel)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProcessRequestInterface: Hashable, CustomStringConvertible {
  var formToken: String
  var errorCodes: ErrorCodesInterface
  var timeoutInSeconds: Int64? = nil
  var options: LyraProcessOptionsInterface? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProcessRequestInterface? {
    let formToken = pigeonVar_list[0] as! String
    let errorCodes = pigeonVar_list[1] as! ErrorCodesInterface
    let timeoutInSeconds: Int64? = nilOrValue(pigeonVar_list[2])
    let options: LyraProcessOptionsInterface? = nilOrValue(pigeonVar_list[3])

    return ProcessRequestInterface(
      formToken: formToken,
      errorCodes: errorCodes,
      timeoutInSeconds: timeoutInSeconds,
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      formToken,
      errorCodes,
      timeoutInSeconds,
      options,
    ]
  }
  static func == (lhs: ProcessRequestInterface, rhs: ProcessRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LyraApiPigeonInternal.deepEquals(lhs.formToken, rhs.formToken) && LyraApiPigeonInternal.deepEquals(lhs.errorCodes, rhs.errorCodes) && LyraApiPigeonInternal.deepEquals(lhs.timeoutInSeconds, rhs.timeoutInSeconds) && LyraApiPigeonInternal.deepEquals(lhs.options, rhs.options)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProcessRequestInterface")
    LyraApiPigeonInternal.deepHash(value: formToken, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: errorCodes, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: timeoutInSeconds, hasher: &hasher)
    LyraApiPigeonInternal.deepHash(value: options, hasher: &hasher)
  }

  public var description: String {
    return "ProcessRequestInterface(formToken: \(String(describing: formToken)), errorCodes: \(String(describing: errorCodes)), timeoutInSeconds: \(String(describing: timeoutInSeconds)), options: \(String(describing: options)))"
  }
}

private class LyraApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ErrorCodesInterface.fromList(self.readValue() as! [Any?])
    case 130:
      return LyraInitializeOptionsInterface.fromList(self.readValue() as! [Any?])
    case 131:
      return LyraKeyInterface.fromList(self.readValue() as! [Any?])
    case 132:
      return LyraProcessOptionsInterface.fromList(self.readValue() as! [Any?])
    case 133:
      return ProcessRequestInterface.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LyraApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ErrorCodesInterface {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LyraInitializeOptionsInterface {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LyraKeyInterface {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LyraProcessOptionsInterface {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ProcessRequestInterface {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LyraApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LyraApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LyraApiPigeonCodecWriter(data: data)
  }
}

class LyraApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LyraApiPigeonCodec(readerWriter: LyraApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LyraHostApi {
  func initialize(lyraKey: LyraKeyInterface, completion: @escaping (Result<LyraKeyInterface, Error>) -> Void)
  func getFormTokenVersion(completion: @escaping (Result<Int64, Error>) -> Void)
  func process(request: ProcessRequestInterface, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LyraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LyraApiPigeonCodec.shared }
  /// Sets up an instance of `LyraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LyraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let lyraKeyArg = args[0] as! LyraKeyInterface
        api.initialize(lyraKey: lyraKeyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let getFormTokenVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.getFormTokenVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFormTokenVersionChannel.setMessageHandler { _, reply in
        api.getFormTokenVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFormTokenVersionChannel.setMessageHandler(nil)
    }
    let processChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.process\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      processChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ProcessRequestInterface
        api.process(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      processChannel.setMessageHandler(nil)
    }
  }
}
