// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Infos;

@interface Infos : NSObject
+ (instancetype)makeWithInfo1:(nullable NSString *)info1
    info2:(nullable NSString *)info2;
@property(nonatomic, copy, nullable) NSString * info1;
@property(nonatomic, copy, nullable) NSString * info2;
@end

/// The codec used by InfosApi.
NSObject<FlutterMessageCodec> *InfosApiGetCodec(void);

@protocol InfosApi
- (nullable Infos *)searchWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void InfosApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<InfosApi> *_Nullable api);

NS_ASSUME_NONNULL_END
