// Autogenerated from Pigeon (v4.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LyraInitializeOptionsInterface;
@class LyraKeyInterface;

@interface LyraInitializeOptionsInterface : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithApiServerName:(NSString *)apiServerName
    nfcEnabled:(nullable NSNumber *)nfcEnabled
    cardScanningEnabled:(nullable NSNumber *)cardScanningEnabled;
@property(nonatomic, copy) NSString * apiServerName;
@property(nonatomic, strong, nullable) NSNumber * nfcEnabled;
@property(nonatomic, strong, nullable) NSNumber * cardScanningEnabled;
@end

@interface LyraKeyInterface : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPublicKey:(NSString *)publicKey
    options:(LyraInitializeOptionsInterface *)options;
@property(nonatomic, copy) NSString * publicKey;
@property(nonatomic, strong) LyraInitializeOptionsInterface * options;
@end

/// The codec used by LyraHostApi.
NSObject<FlutterMessageCodec> *LyraHostApiGetCodec(void);

@protocol LyraHostApi
- (void)initializeLyraKey:(LyraKeyInterface *)lyraKey completion:(void(^)(LyraKeyInterface *_Nullable, FlutterError *_Nullable))completion;
- (void)getFormTokenVersionWithCompletion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void LyraHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LyraHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
