// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "lyra_api.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}


static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface ErrorCodesInterface ()
+ (ErrorCodesInterface *)fromList:(NSArray<id> *)list;
+ (nullable ErrorCodesInterface *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface LyraInitializeOptionsInterface ()
+ (LyraInitializeOptionsInterface *)fromList:(NSArray<id> *)list;
+ (nullable LyraInitializeOptionsInterface *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface LyraKeyInterface ()
+ (LyraKeyInterface *)fromList:(NSArray<id> *)list;
+ (nullable LyraKeyInterface *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ProcessRequestInterface ()
+ (ProcessRequestInterface *)fromList:(NSArray<id> *)list;
+ (nullable ProcessRequestInterface *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation ErrorCodesInterface
+ (instancetype)makeWithPaymentCancelledByUser:(NSString *)paymentCancelledByUser {
  ErrorCodesInterface* pigeonResult = [[ErrorCodesInterface alloc] init];
  pigeonResult.paymentCancelledByUser = paymentCancelledByUser;
  return pigeonResult;
}
+ (ErrorCodesInterface *)fromList:(NSArray<id> *)list {
  ErrorCodesInterface *pigeonResult = [[ErrorCodesInterface alloc] init];
  pigeonResult.paymentCancelledByUser = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable ErrorCodesInterface *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ErrorCodesInterface fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.paymentCancelledByUser ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ErrorCodesInterface *other = (ErrorCodesInterface *)object;
  return FLTPigeonDeepEquals(self.paymentCancelledByUser, other.paymentCancelledByUser);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.paymentCancelledByUser);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"ErrorCodesInterface(paymentCancelledByUser: %@)", self.paymentCancelledByUser];
}
@end

@implementation LyraInitializeOptionsInterface
+ (instancetype)makeWithApiServerName:(NSString *)apiServerName
    nfcEnabled:(nullable NSNumber *)nfcEnabled
    cardScanningEnabled:(nullable NSNumber *)cardScanningEnabled
    applePayMerchantId:(nullable NSString *)applePayMerchantId
    applePayMerchantName:(nullable NSString *)applePayMerchantName {
  LyraInitializeOptionsInterface* pigeonResult = [[LyraInitializeOptionsInterface alloc] init];
  pigeonResult.apiServerName = apiServerName;
  pigeonResult.nfcEnabled = nfcEnabled;
  pigeonResult.cardScanningEnabled = cardScanningEnabled;
  pigeonResult.applePayMerchantId = applePayMerchantId;
  pigeonResult.applePayMerchantName = applePayMerchantName;
  return pigeonResult;
}
+ (LyraInitializeOptionsInterface *)fromList:(NSArray<id> *)list {
  LyraInitializeOptionsInterface *pigeonResult = [[LyraInitializeOptionsInterface alloc] init];
  pigeonResult.apiServerName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.nfcEnabled = GetNullableObjectAtIndex(list, 1);
  pigeonResult.cardScanningEnabled = GetNullableObjectAtIndex(list, 2);
  pigeonResult.applePayMerchantId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.applePayMerchantName = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable LyraInitializeOptionsInterface *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [LyraInitializeOptionsInterface fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.apiServerName ?: [NSNull null],
    self.nfcEnabled ?: [NSNull null],
    self.cardScanningEnabled ?: [NSNull null],
    self.applePayMerchantId ?: [NSNull null],
    self.applePayMerchantName ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  LyraInitializeOptionsInterface *other = (LyraInitializeOptionsInterface *)object;
  return FLTPigeonDeepEquals(self.apiServerName, other.apiServerName) && FLTPigeonDeepEquals(self.nfcEnabled, other.nfcEnabled) && FLTPigeonDeepEquals(self.cardScanningEnabled, other.cardScanningEnabled) && FLTPigeonDeepEquals(self.applePayMerchantId, other.applePayMerchantId) && FLTPigeonDeepEquals(self.applePayMerchantName, other.applePayMerchantName);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.apiServerName);
  result = result * 31 + FLTPigeonDeepHash(self.nfcEnabled);
  result = result * 31 + FLTPigeonDeepHash(self.cardScanningEnabled);
  result = result * 31 + FLTPigeonDeepHash(self.applePayMerchantId);
  result = result * 31 + FLTPigeonDeepHash(self.applePayMerchantName);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"LyraInitializeOptionsInterface(apiServerName: %@, nfcEnabled: %@, cardScanningEnabled: %@, applePayMerchantId: %@, applePayMerchantName: %@)", self.apiServerName, self.nfcEnabled, self.cardScanningEnabled, self.applePayMerchantId, self.applePayMerchantName];
}
@end

@implementation LyraKeyInterface
+ (instancetype)makeWithPublicKey:(NSString *)publicKey
    options:(LyraInitializeOptionsInterface *)options {
  LyraKeyInterface* pigeonResult = [[LyraKeyInterface alloc] init];
  pigeonResult.publicKey = publicKey;
  pigeonResult.options = options;
  return pigeonResult;
}
+ (LyraKeyInterface *)fromList:(NSArray<id> *)list {
  LyraKeyInterface *pigeonResult = [[LyraKeyInterface alloc] init];
  pigeonResult.publicKey = GetNullableObjectAtIndex(list, 0);
  pigeonResult.options = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable LyraKeyInterface *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [LyraKeyInterface fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.publicKey ?: [NSNull null],
    self.options ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  LyraKeyInterface *other = (LyraKeyInterface *)object;
  return FLTPigeonDeepEquals(self.publicKey, other.publicKey) && FLTPigeonDeepEquals(self.options, other.options);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.publicKey);
  result = result * 31 + FLTPigeonDeepHash(self.options);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"LyraKeyInterface(publicKey: %@, options: %@)", self.publicKey, self.options];
}
@end

@implementation ProcessRequestInterface
+ (instancetype)makeWithFormToken:(NSString *)formToken
    errorCodes:(ErrorCodesInterface *)errorCodes
    timeoutInSeconds:(nullable NSNumber *)timeoutInSeconds {
  ProcessRequestInterface* pigeonResult = [[ProcessRequestInterface alloc] init];
  pigeonResult.formToken = formToken;
  pigeonResult.errorCodes = errorCodes;
  pigeonResult.timeoutInSeconds = timeoutInSeconds;
  return pigeonResult;
}
+ (ProcessRequestInterface *)fromList:(NSArray<id> *)list {
  ProcessRequestInterface *pigeonResult = [[ProcessRequestInterface alloc] init];
  pigeonResult.formToken = GetNullableObjectAtIndex(list, 0);
  pigeonResult.errorCodes = GetNullableObjectAtIndex(list, 1);
  pigeonResult.timeoutInSeconds = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable ProcessRequestInterface *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ProcessRequestInterface fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.formToken ?: [NSNull null],
    self.errorCodes ?: [NSNull null],
    self.timeoutInSeconds ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  ProcessRequestInterface *other = (ProcessRequestInterface *)object;
  return FLTPigeonDeepEquals(self.formToken, other.formToken) && FLTPigeonDeepEquals(self.errorCodes, other.errorCodes) && FLTPigeonDeepEquals(self.timeoutInSeconds, other.timeoutInSeconds);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.formToken);
  result = result * 31 + FLTPigeonDeepHash(self.errorCodes);
  result = result * 31 + FLTPigeonDeepHash(self.timeoutInSeconds);
  return result;
}
- (NSString *)description {
  return [NSString stringWithFormat:@"ProcessRequestInterface(formToken: %@, errorCodes: %@, timeoutInSeconds: %@)", self.formToken, self.errorCodes, self.timeoutInSeconds];
}
@end

@interface nullLyraApiPigeonCodecReader : FlutterStandardReader
@end
@implementation nullLyraApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [ErrorCodesInterface fromList:[self readValue]];
    case 130: 
      return [LyraInitializeOptionsInterface fromList:[self readValue]];
    case 131: 
      return [LyraKeyInterface fromList:[self readValue]];
    case 132: 
      return [ProcessRequestInterface fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullLyraApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullLyraApiPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[ErrorCodesInterface class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[LyraInitializeOptionsInterface class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[LyraKeyInterface class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ProcessRequestInterface class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullLyraApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullLyraApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullLyraApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullLyraApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetLyraApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullLyraApiPigeonCodecReaderWriter *readerWriter = [[nullLyraApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpLyraHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LyraHostApi> *api) {
  SetUpLyraHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpLyraHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LyraHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.initialize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetLyraApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initializeLyraKey:completion:)], @"LyraHostApi api (%@) doesn't respond to @selector(initializeLyraKey:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        LyraKeyInterface *arg_lyraKey = GetNullableObjectAtIndex(args, 0);
        [api initializeLyraKey:arg_lyraKey completion:^(LyraKeyInterface *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.getFormTokenVersion", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetLyraApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFormTokenVersionWithCompletion:)], @"LyraHostApi api (%@) doesn't respond to @selector(getFormTokenVersionWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getFormTokenVersionWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_lyra_platform_interface.LyraHostApi.process", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetLyraApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(processRequest:completion:)], @"LyraHostApi api (%@) doesn't respond to @selector(processRequest:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        ProcessRequestInterface *arg_request = GetNullableObjectAtIndex(args, 0);
        [api processRequest:arg_request completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
