// Autogenerated from Pigeon (v4.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "lyra_api.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface ErrorCodesInterface ()
+ (ErrorCodesInterface *)fromMap:(NSDictionary *)dict;
+ (nullable ErrorCodesInterface *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface LyraInitializeOptionsInterface ()
+ (LyraInitializeOptionsInterface *)fromMap:(NSDictionary *)dict;
+ (nullable LyraInitializeOptionsInterface *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface LyraKeyInterface ()
+ (LyraKeyInterface *)fromMap:(NSDictionary *)dict;
+ (nullable LyraKeyInterface *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface ProcessRequestInterface ()
+ (ProcessRequestInterface *)fromMap:(NSDictionary *)dict;
+ (nullable ProcessRequestInterface *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation ErrorCodesInterface
+ (instancetype)makeWithPaymentCancelledByUser:(NSString *)paymentCancelledByUser {
  ErrorCodesInterface* pigeonResult = [[ErrorCodesInterface alloc] init];
  pigeonResult.paymentCancelledByUser = paymentCancelledByUser;
  return pigeonResult;
}
+ (ErrorCodesInterface *)fromMap:(NSDictionary *)dict {
  ErrorCodesInterface *pigeonResult = [[ErrorCodesInterface alloc] init];
  pigeonResult.paymentCancelledByUser = GetNullableObject(dict, @"paymentCancelledByUser");
  NSAssert(pigeonResult.paymentCancelledByUser != nil, @"");
  return pigeonResult;
}
+ (nullable ErrorCodesInterface *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [ErrorCodesInterface fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"paymentCancelledByUser" : (self.paymentCancelledByUser ?: [NSNull null]),
  };
}
@end

@implementation LyraInitializeOptionsInterface
+ (instancetype)makeWithApiServerName:(NSString *)apiServerName
    nfcEnabled:(nullable NSNumber *)nfcEnabled
    cardScanningEnabled:(nullable NSNumber *)cardScanningEnabled {
  LyraInitializeOptionsInterface* pigeonResult = [[LyraInitializeOptionsInterface alloc] init];
  pigeonResult.apiServerName = apiServerName;
  pigeonResult.nfcEnabled = nfcEnabled;
  pigeonResult.cardScanningEnabled = cardScanningEnabled;
  return pigeonResult;
}
+ (LyraInitializeOptionsInterface *)fromMap:(NSDictionary *)dict {
  LyraInitializeOptionsInterface *pigeonResult = [[LyraInitializeOptionsInterface alloc] init];
  pigeonResult.apiServerName = GetNullableObject(dict, @"apiServerName");
  NSAssert(pigeonResult.apiServerName != nil, @"");
  pigeonResult.nfcEnabled = GetNullableObject(dict, @"nfcEnabled");
  pigeonResult.cardScanningEnabled = GetNullableObject(dict, @"cardScanningEnabled");
  return pigeonResult;
}
+ (nullable LyraInitializeOptionsInterface *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [LyraInitializeOptionsInterface fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"apiServerName" : (self.apiServerName ?: [NSNull null]),
    @"nfcEnabled" : (self.nfcEnabled ?: [NSNull null]),
    @"cardScanningEnabled" : (self.cardScanningEnabled ?: [NSNull null]),
  };
}
@end

@implementation LyraKeyInterface
+ (instancetype)makeWithPublicKey:(NSString *)publicKey
    options:(LyraInitializeOptionsInterface *)options {
  LyraKeyInterface* pigeonResult = [[LyraKeyInterface alloc] init];
  pigeonResult.publicKey = publicKey;
  pigeonResult.options = options;
  return pigeonResult;
}
+ (LyraKeyInterface *)fromMap:(NSDictionary *)dict {
  LyraKeyInterface *pigeonResult = [[LyraKeyInterface alloc] init];
  pigeonResult.publicKey = GetNullableObject(dict, @"publicKey");
  NSAssert(pigeonResult.publicKey != nil, @"");
  pigeonResult.options = [LyraInitializeOptionsInterface nullableFromMap:GetNullableObject(dict, @"options")];
  NSAssert(pigeonResult.options != nil, @"");
  return pigeonResult;
}
+ (nullable LyraKeyInterface *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [LyraKeyInterface fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"publicKey" : (self.publicKey ?: [NSNull null]),
    @"options" : (self.options ? [self.options toMap] : [NSNull null]),
  };
}
@end

@implementation ProcessRequestInterface
+ (instancetype)makeWithFormToken:(NSString *)formToken
    errorCodes:(ErrorCodesInterface *)errorCodes {
  ProcessRequestInterface* pigeonResult = [[ProcessRequestInterface alloc] init];
  pigeonResult.formToken = formToken;
  pigeonResult.errorCodes = errorCodes;
  return pigeonResult;
}
+ (ProcessRequestInterface *)fromMap:(NSDictionary *)dict {
  ProcessRequestInterface *pigeonResult = [[ProcessRequestInterface alloc] init];
  pigeonResult.formToken = GetNullableObject(dict, @"formToken");
  NSAssert(pigeonResult.formToken != nil, @"");
  pigeonResult.errorCodes = [ErrorCodesInterface nullableFromMap:GetNullableObject(dict, @"errorCodes")];
  NSAssert(pigeonResult.errorCodes != nil, @"");
  return pigeonResult;
}
+ (nullable ProcessRequestInterface *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [ProcessRequestInterface fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"formToken" : (self.formToken ?: [NSNull null]),
    @"errorCodes" : (self.errorCodes ? [self.errorCodes toMap] : [NSNull null]),
  };
}
@end

@interface LyraHostApiCodecReader : FlutterStandardReader
@end
@implementation LyraHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [ErrorCodesInterface fromMap:[self readValue]];
    
    case 129:     
      return [LyraInitializeOptionsInterface fromMap:[self readValue]];
    
    case 130:     
      return [LyraKeyInterface fromMap:[self readValue]];
    
    case 131:     
      return [ProcessRequestInterface fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface LyraHostApiCodecWriter : FlutterStandardWriter
@end
@implementation LyraHostApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[ErrorCodesInterface class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[LyraInitializeOptionsInterface class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[LyraKeyInterface class]]) {
    [self writeByte:130];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[ProcessRequestInterface class]]) {
    [self writeByte:131];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface LyraHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation LyraHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[LyraHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[LyraHostApiCodecReader alloc] initWithData:data];
}
@end


NSObject<FlutterMessageCodec> *LyraHostApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    LyraHostApiCodecReaderWriter *readerWriter = [[LyraHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void LyraHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LyraHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.LyraHostApi.initialize"
        binaryMessenger:binaryMessenger
        codec:LyraHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initializeLyraKey:completion:)], @"LyraHostApi api (%@) doesn't respond to @selector(initializeLyraKey:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        LyraKeyInterface *arg_lyraKey = GetNullableObjectAtIndex(args, 0);
        [api initializeLyraKey:arg_lyraKey completion:^(LyraKeyInterface *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.LyraHostApi.getFormTokenVersion"
        binaryMessenger:binaryMessenger
        codec:LyraHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFormTokenVersionWithCompletion:)], @"LyraHostApi api (%@) doesn't respond to @selector(getFormTokenVersionWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getFormTokenVersionWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.LyraHostApi.process"
        binaryMessenger:binaryMessenger
        codec:LyraHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(processRequest:completion:)], @"LyraHostApi api (%@) doesn't respond to @selector(processRequest:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        ProcessRequestInterface *arg_request = GetNullableObjectAtIndex(args, 0);
        [api processRequest:arg_request completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
